Wxb2018/Wxb2018/Controllers/DutyLogController.cs
using System;

using System.Web.Mvc;
using WXB.Bussiness.Common;
using WXB.Bussiness.Service;
using WXB.Bussiness.ViewModels;
using Wxb2018.Filters;

namespace Wxb2018.Controllers
{
    public class DutyLogController : BaseController
    {

        #region 获取值班记录
        /// <summary>
        /// 获取登录记录
        /// </summary>
        /// <returns></returns>
        [AuthorizationFilter]
        public ActionResult Index()
        {
            PageVM<DutyLogVM> pageDuty = new DutyLogService().GetDutyLogPageData(new PageQuery() { PageSize = 8 });

            if (pageDuty == null) pageDuty = new PageVM<DutyLogVM>();

            return View(pageDuty);
        }
        #endregion

        #region 上班
        /// <summary>
        /// 上班
        /// </summary>
        /// <returns></returns>
        [AuthorizationFilter]
        public ActionResult Add()
        {

            try
            {
                DutyLogVM vm = new DutyLogVM()
                {
                    UserID = UserData.UserId,
                    UserName = UserData.Name,
                    StartTime = DateTime.Now
                };

                vm = new DutyLogService().AddDutyLog(vm);
                if (vm == null)
                {
                    return Json(new
                    {
                        Code = -400,
                        Msg = "参数错误"
                    });
                }

                #region 日志

                var log = new LogVM()
                {
                    Operator = this.UserData.Name,
                    OperatorID = this.UserData.UserId,
                    RoleType = this.UserData.RoleType,
                    OperateTime = DateTime.Now,
                    OperateType = vm.ID.HasValue ? (int)EnumOperateType.上班 : (int)EnumOperateType.上班
                };

                log.OperateDescribe = ((EnumOperateType)log.OperateType).ToString();
                Logger.AddLog(log);

                #endregion

                return Json(new
                {
                    Code = 200,
                    Msg = "添加成功",
                    Data = vm
                });
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        #endregion

        #region 下班
        /// <summary>
        /// 下班
        /// </summary>
        /// <returns></returns>
        [AuthorizationFilter]
        public ActionResult UpdateDutyStatus(DutyLogVM vm)
        {

            if (vm == null || !vm.ID.HasValue)
            {
                return Json(new
                {
                    Code = -400,
                    Msg = "参数错误"
                });
            }

            try
            {

                vm.EndTime = DateTime.Now;

                vm = new DutyLogService().UpdateDutyStatus(vm);
                if (vm == null)
                {
                    return Json(new
                    {
                        Code = -400,
                        Msg = "参数错误"
                    });
                }

                #region 日志

                var log = new LogVM()
                {
                    Operator = this.UserData.Name,
                    OperatorID = this.UserData.UserId,
                    RoleType = this.UserData.RoleType,
                    OperateTime = DateTime.Now,
                    OperateType = vm.ID.HasValue ? (int)EnumOperateType.下班 : (int)EnumOperateType.下班
                };

                log.OperateDescribe = ((EnumOperateType)log.OperateType).ToString();
                Logger.AddLog(log);

                #endregion

                return Json(new
                {
                    Code = 200,
                    Msg = "更新成功",
                    Data = vm
                });
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        #endregion

        #region 获取当前登录用户的值班信息
        public ActionResult GetUserDutyLog()
        {

            if (UserData == null || !UserData.UserId.HasValue)
            {
                return Json(new
                {
                    Code = -401,
                    Msg = "请先登录"
                }, JsonRequestBehavior.AllowGet);
            }

            OnDutyVM vm = new DutyLogService().GetUserDutyLog(UserData.UserId.Value);

            if (vm == null)
            {
                return Json(new
                   {
                       Code = -200,
                       Msg = "暂无值班人员"
                   }, JsonRequestBehavior.AllowGet);
            }

            if (string.IsNullOrEmpty(vm.CurrentDutyUser) && vm.OtherDutyUser.Count > 0)
            {
                return Json(new
                {
                    Code = 201,
                    Msg = "当前用户还未值班，存在未标记下班的用户",
                    Data = vm
                }, JsonRequestBehavior.AllowGet);
            }

            return Json(new
            {
                Code = 200,
                Msg = "当前用户正在值班",
                Data = vm
            }, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region 获取值班记录(分页)
        /// <summary>
        /// 获取值班记录
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public ActionResult GetDutyLogPageData(PageQuery query)
        {
            if (query == null) query = new NoticeQuery();

            if (!query.PageIndex.HasValue)
                query.PageIndex = 1;

            if (!query.PageSize.HasValue)
                query.PageSize = 8;

            PageVM<DutyLogVM> list = new DutyLogService().GetDutyLogPageData(query);

            if (list == null || list.Data == null || list.Data.Count == 0)
            {
                return Json(new
                {
                    Code = -200,
                    Msg = "暂无数据"
                });
            }

            return Json(new
            {
                Code = 200,
                Msg = "获取成功",
                Data = list
            });
        }
        #endregion

    }
}

Wxb2018/Wxb2018/Controllers/ResponseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using WXB.Bussiness.Service;
using WXB.Bussiness.ViewModels;
using WXB.Bussiness.Common;
using WXB.Bussiness.Models;

namespace Wxb2018.Controllers
{
    public class ResponseController : BaseController
    {

        #region 获取响应状态
        /// <summary>
        /// 获取响应状态
        /// </summary>
        /// <returns></returns>
        public ActionResult GetResponseStatus()
        {
            ResponseStatusView resVM = new ResponseStatusService().GetResponseStatus();
            if (resVM == null)
            {
                return Json(new { Code = -200, Msg = "暂无数据" }, JsonRequestBehavior.AllowGet);
            }

            return Json(new
            {
                Code = 200,
                Msg = "获取成功",
                Data = new
                {
                    ID = resVM.ID,
                    Status = resVM.Status,
                    StatusText = ((EnumResponseStatus)resVM.Status).ToString()
                }
            }, JsonRequestBehavior.AllowGet);
        }

        #endregion

        #region 编辑
        public ActionResult Edit(ResponseQuery query)
        {
            if (query == null) query = new ResponseQuery() { ID = 0 };

            ResponseStatusView vm = new ResponseStatusService().GetResponseStatusByID(query.ID.Value);
            return View("Edit", vm);
        }
        #endregion

        #region 保存
        /// <summary>
        /// 保存
        /// </summary>
        /// <param name="vm"></param>
        /// <returns></returns>
        public ActionResult SaveResponse(ResponseStatusView vm)
        {

            if (vm == null)
            {
                return Json(new
                {
                    Code = -400,
                    Msg = "参数不能为空",
                });
            }

            try
            {
                ResponseStatusService rpSV = new ResponseStatusService();

                vm.Inputer = UserData.Name;
                vm.InputerID = UserData.UserId;
                vm = rpSV.SaveResponse(vm);

                #region 日志

                var log = new LogVM()
                {
                    Operator = this.UserData.Name,
                    OperatorID = this.UserData.UserId,
                    RoleType = this.UserData.RoleType,
                    OperateTime = DateTime.Now,
                    OperateType = (int)EnumOperateType.编辑
                };

                log.OperateDescribe = ((EnumOperateType)log.OperateType).ToString()+"响应状态";
                Logger.AddLog(log);

                #endregion

                return Json(new
                {
                    Code = 200,
                    Msg = "保存成功",
                    Data = new
                    {
                        ID = vm.ID,
                        Status = vm.Status,
                        StatusText = ((EnumResponseStatus)vm.Status).ToString()
                    }
                });
            }
            catch (Exception ex)
            {
                throw ex;
            }

        }
        #endregion
    }
}

Wxb2018/Wxb2018/Views/Shared/AccountPartial.cshtml
@{
    Layout = null;
}
<!-- 登录弹窗 -->
<div class="denglu-box center-1" style="display:none;" id="login-Div">
    <div class="enter-2">
        <div class="title-close">登录<a class="closeBtn"></a></div>
        <form>
            <div class="error" id="lg-error">密码输入错误，请重新输入。</div>
            <ul>
                <li><input id="lg-userName" autocomplete="off" class="text-2" name="textfield" type="text" placeholder="请输入客户编号或手机号" value="" /></li>
                <li><input id="lg-password" type="password" placeholder="请输入登录密码" class="password-2" /></li>
                <li class="ckbox" style="display:none;"><label><input id="lg-rememberMe" type="checkbox" /><em>记住密码</em></label></li>
            </ul>
            <div class="denglu-but"><a class="error-btn" id="lg-btn" href="javascript:void(0);">登录</a></div>
        </form>
        @*<div class="closeBtn"></div>*@
    </div>
</div>

<script type="text/javascript">

    $(function () {

        var regex = {
            phone: "^(0|86|17951)?1[0-9]{10}$",
            password: "^[0-9a-zA-Z]{6,16}$",
            code: "^[0-9a-zA-Z]{1,20}$",
            danger: "</?[a-zA-Z0-9]+>",
            postCode: "^[1-9][0-9]{5}$",
            number: '^\\d+$',
            integer: '^[-\\+]?\\d+$',
            double: '^[-\\+]?\\d+(\\.\\d+)?$',
            verCode: "^[0-9]{6}$"
        };

        // 列表界面'登录'
        $('.denglu').on('click', function () {
            alertLoginWin();
        });

        //登录弹窗
        function alertLoginWin() {

            if ($('.denglu-box').attr('data-opening') == '1') {
                return;
            }

            var options = $.extend({ closeBtn: true, shade: 0.3 }, window.layerOptions || {});
            layer.open({
                title: false,
                type: 1,
                skin: 'login-layer',
                area: ['400px', '290px'],
                closeBtn: false,
                shade: options.shade,
                move: false,
                content: $('.denglu-box'),
                success: function (layero, index) {

                    $('.denglu-box').find('.closeBtn').data('dengluindex', index);
                    if (!options.closeBtn) {
                        $('.denglu-box').find('.closeBtn').hide();
                    }
                    $(document.body).attr('data-opening', '1');
                }
            });
        }

        //关闭登录弹窗
        $('.closeBtn').on('click', function () {

            var denglu_index = $(this).data('dengluindex')
            layer.close(denglu_index);
            $(document.body).attr('data-opening', '0');
        });

        //dialog界面'登录'
        $("#lg-btn").on("click", function () {

            hideTip();

            var user = vaildUser();
            if (!user) return;

            showTip("登入中...");

            var loginUrl = '@(Url.Action("Login","Account"))';
            $.post(loginUrl, user, function (data) {

                if (data.Code == 200) {

                    //刷新界面
                    location.href = '@Url.Content("~/")';
                    //关闭dialog
                    var denglu_index = $("#lg-btn").data('dengluindex')
                    layer.close(denglu_index);

                } else {
                    showTip(data.Msg);
                }
            });
        });

        $(document).on("keydown", function (e) {
            if (e.keyCode == 13) {
                if ($("#login-Div").css("display") == "block") {
                    $("#lg-btn").click();
                } else {
                    $("#reg-btn").click();
                }
            }
        });

        //判断用户输入信息
        function vaildUser() {

            var UserName = $.trim($("#lg-userName").val());
            //if (!(new RegExp(regex.phone).test(UserName) || /^[a-zA-Z0-9_\.\u4e00-\u9fa5]{2,25}$/.test(UserName))) {
            //    showTip("请输入正确的客户编号或手机号！");
            //    return null;
            //}

            var password = $.trim($("#lg-password").val());
            //if (!new RegExp(regex.password).test(password)) {
            //    showTip("密码由6-16位数字或字母组成，请重新输入！");
            //    return null;
            //}

            return {
                userName: UserName,
                password: password,
                isRememberPwd: !!$("#lg-rememberMe:checked")[0]
            };
        }

        function showTip(msg, success) {
            if (success) {

            } else {
                $("#lg-error").show().text(msg);
            }
        }

        function hideTip() {
            $("#lg-error").hide();
        }

        $.alertLoginWin = alertLoginWin;
        window.alertLoginWin = alertLoginWin;
    });

</script>

Wxb2018/Wxb2018/Views/Shared/LoginHeadPartial.cshtml
@using Wxb2018
@{
    WFFormPrincipal loginUser = User as WFFormPrincipal;
    WFFormsAuthentication userInfo = loginUser == null ? new WFFormsAuthentication() : loginUser.UserData;
}

<div class="user-info">
    <em class="info-title">欢迎您,</em>
    <div class="info-name">
        <a href="javascript:void(0);" class="acc_name">
            <span>@(userInfo.TrueName)</span>
        </a>
        <ul class="info-account">
            <li><a href="@(Url.Action("logout", "account", new { redirectUrl=Url.Action("login","account") }))">退出</a></li>
        </ul>
    </div>
</div>

<script type="text/javascript">

    $(function () {


        $('.info-name').hover(function () {

            $('.user-info').css('background-color', '#333');
            $('.info-account').show();
        }, function () {
            
            $('.user-info').css('background-color', '#000');
            $('.info-account').hide();
        });
    });
</script>

Wxb2018/Wxb2018/Views/Shared/_Layout.cshtml
@using WXB.Bussiness.Common
@{
    var isLogin = Request.IsAuthenticated;
    WFFormPrincipal loginUser = User as WFFormPrincipal;
    WFFormsAuthentication userInfo = loginUser == null ? new WFFormsAuthentication() : loginUser.UserData;
}
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width" />
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <link href="~/content/css/common.css" rel="stylesheet" type="text/css" />
    <link href="~/content/css/base.css" rel="stylesheet" type="text/css" />
    <link href="~/content/iconfont/iconfont.css" rel="stylesheet" type="text/css" />
    <link href="~/content/plugins/pagination/pagination.css" rel="stylesheet" type="text/css" />
    @RenderSection("head", false)

    <script type="text/javascript" src="~/Content/plugins/jquery-1.8.3.min.js"></script>
    <script type="text/javascript" src="~/Content/plugins/layer/layer.js"></script>
    <script type="text/javascript" src="~/Content/plugins/laydate/laydate.js"></script>
    <script type="text/javascript" src="~/Content/plugins/pagination/jquery.pagination.js"></script>
</head>
<body>

    <!--登录成功头部-->
    <div id="accountDiv"></div>
    <!--响应状态编辑-->
    <div id="responseDiv">
        <div class="rp-title"><span class="title-text">响应状态编辑</span></div>
        <div class="rp-content"></div>
        <div class="rp-footer">
            <span class="btn-save saveResponse">保存</span>
            <span class="btn-cancel cancelResponse">取消</span>
        </div>
    </div>

    <div class="topBar">
        <div class="mCon">
            <div class="topcon clearfix">

                @if (isLogin && userInfo.Flag == (int)EnumIsAdmin.是)
                {
                    <!--值班/登录记录-->
                    <div class="record">
                        <a class="record-text">
                            <span class="iconfont icon-record"></span><span>记录</span>
                        </a>
                        <ul class="record-type">
                            <li><a href="@Url.Action("index","dutylog")" style="display:inline-block;">值班记录</a></li>
                            <li><a href="@Url.Action("index","log")" style="display:inline-block;">登录记录</a></li>
                        </ul>
                    </div>
                }

                @if (isLogin)
                {
                     <!--响应状态、值班-->
                    <div class="response">
                        <span class="response-text"><a class="iconfont icon-gear" href="javascript:void(0);"></a><a class="response-icon">响应状态：</a></span>
                        <span class="response-val" data-status="1" data-id="">应急</span>
                        <span style="margin-left:10px;display:none;" class="onduty-text">值班人员：</span>
                        <span class="onduty-names"></span>
                    </div>
                }

                <!--登录-->
                <div class="login">
                    <span>
                        <a href="javascript:void(0);" class="loginBtn denglu" id="btnconf">登录</a>
                    </span>
                </div>


                @if (isLogin)
                {
                    <!--值班-->
                    <div class="punch" style="float:right;" data-dutyid="">
                        <span class="iconfont icon-punchin"></span><span class="punchin-text">上班</span>
                        <span class="iconfont icon-punchout"></span> <span class="punchout-text">下班</span>
                    </div>
                }
            </div>
        </div>
    </div>

    <div class="main">
        @RenderBody()
    </div>

    <div class="footer">
        <div class="footer-content auto">

            <div class="content-one">
                <span>本站所载文章、数据仅供参考，使用前请核实，风险自负。</span>
                <span class="ml20">证劵投资咨询业务资格证书：ZX0069 </span>
                <a target="_blank" class="font-color" href="http://jg.sac.net.cn/pages/publicity/investment-list.html">[证监会信息公示]</a>
                <a target="_blank" class="font-color" href="http://person.sac.net.cn/pages/registration/sac-publicity-finish.html?aoiId=199030">[职业人员信息公示]</a>
            </div>

            <div class="content-two">
                <p>
                    上海证券之星综合研究有限公司<em>联系电话：021-50803180</em><span>投诉电话：021-38429864</span>
                    <a class="font-color" href="http://www.szzy888.com/" style="margin:0px 10px">WWW.SZZY888.COM</a><em style=" margin-right:0">Copyright 2006-@(DateTime.Now.Year) </em>
                    <span class=""><a class="font-color" href="http://www.miibeian.gov.cn/" target="_blank">沪ICP备07015607号</a></span>
                </p>
            </div>
        </div>
    </div>

    <div>
        <input type="hidden" name="isLogin" value="@(Request.IsAuthenticated)" />
        <input type="hidden" name="loginHeadPartialUrl" value="@Url.Action("LoginHeadPartial", "Home")" />
        <input type="hidden" name="accountPartialUrl" value="@Url.Action("AccountPartial", "Home")" />
        <input type="hidden" name="addDutyLogUrl" value="@Url.Action("Add", "DutyLog")" />
        <input type="hidden" name="updateDutyStatusUrl" value="@Url.Action("UpdateDutyStatus", "DutyLog")" />
        <input type="hidden" name="getUserDutyLogUrl" value="@Url.Action("GetUserDutyLog", "DutyLog")" />
        <input type="hidden" name="getResponseStatusUrl" value="@Url.Action("GetResponseStatus", "Response")" />
        <input type="hidden" name="editResponseUrl" value="@Url.Action("edit", "Response")" />
        <input type="hidden" name="saveResponseUrl" value="@Url.Action("SaveResponse", "Response")" />
    </div>
    <script type="text/javascript" src="~/Content/js/layout.js"></script>

    @RenderSection("scripts", false)
</body>
</html>